jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/carExpensesKeystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
