name: RunInstrumentationTests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: macOS-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode Keystore
        env:
            ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
            TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
            mkdir "${TMP_KEYSTORE_FILE_PATH}"
            echo $ENCODED_STRING base64 --decode > "${TMP_KEYSTORE_FILE_PATH}"/carExpensesKeystore.jks

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: 29
          script: ./gradlew connectedCheck
        env:
            SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
            SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
            SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}