name: RunInstrumentationTestsWithStacktrace

on:
  # Manual launch only
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run-tests"
  run-tests:
    runs-on: macOS-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: run tests
          uses: reactivecircus/android-emulator-runner@v1
          with:
            api-level: 29
            script: ./gradlew connectedCheck



